[2025-08-03T00:25:22.879+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: comprehensive_analytics_pipeline.wait_for_taxi_data scheduled__2025-08-02T22:25:20.153064+00:00 [queued]>
[2025-08-03T00:25:22.886+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: comprehensive_analytics_pipeline.wait_for_taxi_data scheduled__2025-08-02T22:25:20.153064+00:00 [queued]>
[2025-08-03T00:25:22.886+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-03T00:25:22.891+0000] {taskinstance.py:1380} INFO - Executing <Task(ExternalTaskSensor): wait_for_taxi_data> on 2025-08-02 22:25:20.153064+00:00
[2025-08-03T00:25:22.894+0000] {standard_task_runner.py:57} INFO - Started process 960 to run task
[2025-08-03T00:25:22.896+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'comprehensive_analytics_pipeline', 'wait_for_taxi_data', 'scheduled__2025-08-02T22:25:20.153064+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/comprehensive_analytics_pipeline.py', '--cfg-path', '/tmp/tmpnt4yxvi1']
[2025-08-03T00:25:22.897+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask wait_for_taxi_data
[2025-08-03T00:25:22.934+0000] {task_command.py:415} INFO - Running <TaskInstance: comprehensive_analytics_pipeline.wait_for_taxi_data scheduled__2025-08-02T22:25:20.153064+00:00 [running]> on host 6fb539098074
[2025-08-03T00:25:22.978+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='comprehensive_analytics_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_taxi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T22:25:20.153064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-02T22:25:20.153064+00:00'
[2025-08-03T00:25:22.978+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_to_iceberg'] in dag nyc_taxi_iceberg_etl on 2025-08-02T22:25:20.153064+00:00 ... 
[2025-08-03T00:26:23.046+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_to_iceberg'] in dag nyc_taxi_iceberg_etl on 2025-08-02T22:25:20.153064+00:00 ... 
[2025-08-03T00:27:23.135+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_to_iceberg'] in dag nyc_taxi_iceberg_etl on 2025-08-02T22:25:20.153064+00:00 ... 
[2025-08-03T00:27:23.464+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-03T00:27:23.520+0000] {process_utils.py:131} INFO - Sending 15 to group 960. PIDs of all processes in the group: [960]
[2025-08-03T00:27:23.572+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 960
[2025-08-03T00:27:23.585+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-03T00:27:23.761+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-03T00:27:23.814+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=comprehensive_analytics_pipeline, task_id=wait_for_taxi_data, execution_date=20250802T222520, start_date=20250803T002522, end_date=20250803T002723
[2025-08-03T00:27:23.918+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task wait_for_taxi_data (Task received SIGTERM signal; 960)
[2025-08-03T00:27:23.983+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=960, status='terminated', exitcode=1, started='00:25:22') (960) terminated with exit code 1
[2025-08-03T00:27:23.993+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-08-03T00:27:24.172+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
