[2025-08-03T03:25:22.753+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_weather_etl.spark_process_location_to_iceberg scheduled__2025-08-03T02:25:20.066207+00:00 [queued]>
[2025-08-03T03:25:22.762+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_weather_etl.spark_process_location_to_iceberg scheduled__2025-08-03T02:25:20.066207+00:00 [queued]>
[2025-08-03T03:25:22.763+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-03T03:25:22.826+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): spark_process_location_to_iceberg> on 2025-08-03 02:25:20.066207+00:00
[2025-08-03T03:25:22.829+0000] {standard_task_runner.py:57} INFO - Started process 12541 to run task
[2025-08-03T03:25:22.831+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nyc_weather_etl', 'spark_process_location_to_iceberg', 'scheduled__2025-08-03T02:25:20.066207+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/nyc_weather_etl.py', '--cfg-path', '/tmp/tmph107r06u']
[2025-08-03T03:25:22.832+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask spark_process_location_to_iceberg
[2025-08-03T03:25:22.876+0000] {task_command.py:415} INFO - Running <TaskInstance: nyc_weather_etl.spark_process_location_to_iceberg scheduled__2025-08-03T02:25:20.066207+00:00 [running]> on host 114f606b1815
[2025-08-03T03:25:22.924+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='nyc_weather_etl' AIRFLOW_CTX_TASK_ID='spark_process_location_to_iceberg' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T02:25:20.066207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T02:25:20.066207+00:00'
[2025-08-03T03:25:22.930+0000] {spark_submit.py:218} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-08-03T03:25:22.932+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog --conf spark.sql.catalog.spark_catalog.type=hive --conf spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.iceberg.type=hadoop --conf spark.sql.catalog.iceberg.warehouse=s3a://lakehouse/warehouse --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --jars /opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.4.2.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar --name arrow-spark /opt/***/dags/spark_jobs/location_to_iceberg.py
[2025-08-03T03:25:22.987+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-08-03T03:25:22.988+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-08-03T03:25:22.988+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2025-08-03T03:25:22.996+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog --conf spark.sql.catalog.spark_catalog.type=hive --conf spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.iceberg.type=hadoop --conf spark.sql.catalog.iceberg.warehouse=s3a://lakehouse/warehouse --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --jars /opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.4.2.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar --name arrow-spark /opt/***/dags/spark_jobs/location_to_iceberg.py. Error code is: 1.
[2025-08-03T03:25:22.997+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_weather_etl, task_id=spark_process_location_to_iceberg, execution_date=20250803T022520, start_date=20250803T032522, end_date=20250803T032522
[2025-08-03T03:25:23.003+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 40 for task spark_process_location_to_iceberg (Cannot execute: spark-submit --master yarn --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog --conf spark.sql.catalog.spark_catalog.type=hive --conf spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog --conf spark.sql.catalog.iceberg.type=hadoop --conf spark.sql.catalog.iceberg.warehouse=s3a://lakehouse/warehouse --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --jars /opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.4.2.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar --name arrow-spark /opt/***/dags/spark_jobs/location_to_iceberg.py. Error code is: 1.; 12541)
[2025-08-03T03:25:23.010+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-03T03:25:23.021+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
