[2025-08-03T00:25:24.466+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_weather_etl.validate_weather_data scheduled__2025-08-02T23:25:20.066207+00:00 [queued]>
[2025-08-03T00:25:24.470+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_weather_etl.validate_weather_data scheduled__2025-08-02T23:25:20.066207+00:00 [queued]>
[2025-08-03T00:25:24.470+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-03T00:25:24.551+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): validate_weather_data> on 2025-08-02 23:25:20.066207+00:00
[2025-08-03T00:25:24.555+0000] {standard_task_runner.py:57} INFO - Started process 966 to run task
[2025-08-03T00:25:24.557+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nyc_weather_etl', 'validate_weather_data', 'scheduled__2025-08-02T23:25:20.066207+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/nyc_weather_etl.py', '--cfg-path', '/tmp/tmpg5b7ysq8']
[2025-08-03T00:25:24.561+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask validate_weather_data
[2025-08-03T00:25:24.594+0000] {task_command.py:415} INFO - Running <TaskInstance: nyc_weather_etl.validate_weather_data scheduled__2025-08-02T23:25:20.066207+00:00 [running]> on host 6fb539098074
[2025-08-03T00:25:24.642+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='nyc_weather_etl' AIRFLOW_CTX_TASK_ID='validate_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T23:25:20.066207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-02T23:25:20.066207+00:00'
[2025-08-03T00:25:24.649+0000] {logging_mixin.py:151} INFO - Weather data validation passed. 24 records ready for processing.
[2025-08-03T00:25:24.655+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-08-03T00:25:24.661+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=nyc_weather_etl, task_id=validate_weather_data, execution_date=20250802T232520, start_date=20250803T002524, end_date=20250803T002524
[2025-08-03T00:25:24.698+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T00:25:24.709+0000] {taskinstance.py:2776} INFO - 2 downstream tasks scheduled from follow-on schedule check
