[2025-08-03T00:25:22.869+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: comprehensive_analytics_pipeline.wait_for_weather_data scheduled__2025-08-02T22:25:20.153064+00:00 [queued]>
[2025-08-03T00:25:22.874+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: comprehensive_analytics_pipeline.wait_for_weather_data scheduled__2025-08-02T22:25:20.153064+00:00 [queued]>
[2025-08-03T00:25:22.874+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-03T00:25:22.881+0000] {taskinstance.py:1380} INFO - Executing <Task(ExternalTaskSensor): wait_for_weather_data> on 2025-08-02 22:25:20.153064+00:00
[2025-08-03T00:25:22.884+0000] {standard_task_runner.py:57} INFO - Started process 959 to run task
[2025-08-03T00:25:22.886+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'comprehensive_analytics_pipeline', 'wait_for_weather_data', 'scheduled__2025-08-02T22:25:20.153064+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/comprehensive_analytics_pipeline.py', '--cfg-path', '/tmp/tmpqc9j90y3']
[2025-08-03T00:25:22.888+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask wait_for_weather_data
[2025-08-03T00:25:22.924+0000] {task_command.py:415} INFO - Running <TaskInstance: comprehensive_analytics_pipeline.wait_for_weather_data scheduled__2025-08-02T22:25:20.153064+00:00 [running]> on host 6fb539098074
[2025-08-03T00:25:22.970+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='comprehensive_analytics_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T22:25:20.153064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-02T22:25:20.153064+00:00'
[2025-08-03T00:25:22.971+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-02T22:25:20.153064+00:00 ... 
[2025-08-03T00:26:23.030+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-02T22:25:20.153064+00:00 ... 
[2025-08-03T00:27:23.086+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-02T22:25:20.153064+00:00 ... 
[2025-08-03T00:27:23.462+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-03T00:27:23.549+0000] {process_utils.py:131} INFO - Sending 15 to group 959. PIDs of all processes in the group: [959]
[2025-08-03T00:27:23.574+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 959
[2025-08-03T00:27:23.585+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-03T00:27:23.784+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 285, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-03T00:27:23.813+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=comprehensive_analytics_pipeline, task_id=wait_for_weather_data, execution_date=20250802T222520, start_date=20250803T002522, end_date=20250803T002723
[2025-08-03T00:27:23.939+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task wait_for_weather_data (Task received SIGTERM signal; 959)
[2025-08-03T00:27:24.024+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=959, status='terminated', exitcode=1, started='00:25:22') (959) terminated with exit code 1
[2025-08-03T00:27:24.039+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-08-03T00:27:24.286+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
